### ISSUE TITLE
login is broken

### ISSUE THREAD

**Issue by CloudCray** [haroldtreen/readmeio-sync#13]
Tool attempts to authenticate via:
    https://dash.readme.io/login
…but that is returning an error. It seems that:
    https://dash.readme.io/users/session
is the new method of logging in or something.

If the readmeio-sync tool cannot authenticate the user, instead of throwing an authentication error or 404, it allows the code to continue, and instead gives undefined errors on objects that should have been populated if the user had been authenticated.

The first error I experienced was on "versions", which should be an array, but was never populated:

`````` /usr/local/lib/node_modules/readmeio-sync/lib/requestorFilters.js:103
var filteredVersions = versions.map(function(version) {
                                    ^

TypeError: versions.map is not a function
    at Object.RequestorFilters.versions (/usr/local/lib/node_modules/readmeio-sync/lib/requestorFilters.js:103:37)
    at Request._callback (/usr/local/lib/node_modules/readmeio-sync/lib/requestor.js:145:45)
    at Request.self.callback (/usr/local/lib/node_modules/readmeio-sync/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/readmeio-sync/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/readmeio-sync/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)```
``````

**Comment by haroldtreen** [comment]
Wowza! I did notice the site updated and thought this might happen. I'll give it a look. 

Thanks @CloudCray !

**Comment by haroldtreen** [comment]
Can't seem to reproduce. Was able to download a new project and upload changes fine...

![image](https://cloud.githubusercontent.com/assets/1745854/12225123/775d0cea-b7b8-11e5-8315-b15b1d1d30c0.png)

The session url that you mentioned is actually being used to get the cookie. The login URL is just to scrape the CSFR token from the login page.

**Comment by brian-mann** [comment]
Just tried this tool for the first time and login + everything else worked great.

**Comment by CloudCray** [comment]
Yep, my mistake - looks like it was a configuration issue on my end. My apologies.

However, it would have been nice to receive a more meaningful error message :)

**Comment by haroldtreen** [comment]
Ah, yes - the error handling isn't the best currently. 

What did you need to do to the configuration? I'll add some better error checks so it doesn't happen again :+1: .

**Comment by fharper** [comment]
@CloudCray : what was your mistake? I have the same issues and I correctly set the email/password.

When I print the returned body I get `You have been logged out or your session has expired - please login again.`

**Comment by fharper** [comment]
I found my issue which is different from this one it's now `.com` instead of `.io`, the app doesn't follow redirect. I'll do a PR.
